spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstoreonline
    username: root
    password: 01229696443Vi
    drive-class-name: my.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: update
    show-sql: true

